[package]
name = "gif_maker"
version = "0.1.0"
authors = ["libo <libo@hujiang.com>"]
edition = "2018"

# [lib]
# crate-type = ["cdylib"]

[dependencies]
byteorder = "1"
crc = "1.7.0"
wasm-bindgen = "0.2"
